language:
  - node_js

node_js:
  - "14"

addons:
  chrome: stable

cache:
  yarn: true
  directories:
    - node_modules

before_script:
  - yarn add chromedriver
  - yarn add selenium-side-runner

script:
  - yarn test

notifications:
  email:
    on_success: change
    on_failure: always
